// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A property recommendation AI agent.
 *
 * - propertyRecommendation - A function that handles the property recommendation process.
 * - PropertyRecommendationInput - The input type for the propertyRecommendation function.
 * - PropertyRecommendationOutput - The return type for the propertyRecommendation function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const PropertyRecommendationInputSchema = z.object({
  searchHistory: z
    .string()
    .describe('The user search history, comma separated values of property features, such as number of bedrooms, location, price range and property type.'),
  savedProperties: z
    .string()
    .describe('The list of saved properties, comma separated values of property features, such as number of bedrooms, location, price range and property type.'),
  preferences: z.string().describe('The user preferences for the properties.'),
});
export type PropertyRecommendationInput = z.infer<typeof PropertyRecommendationInputSchema>;

const PropertyRecommendationOutputSchema = z.object({
  propertyRecommendations: z
    .string()
    .describe('The list of recommended properties, each of them with property features, such as number of bedrooms, location, price range and property type.'),
});
export type PropertyRecommendationOutput = z.infer<typeof PropertyRecommendationOutputSchema>;

export async function propertyRecommendation(input: PropertyRecommendationInput): Promise<PropertyRecommendationOutput> {
  return propertyRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'propertyRecommendationPrompt',
  input: {
    schema: z.object({
      searchHistory: z
        .string()
        .describe('The user search history, comma separated values of property features, such as number of bedrooms, location, price range and property type.'),
      savedProperties: z
        .string()
        .describe('The list of saved properties, comma separated values of property features, such as number of bedrooms, location, price range and property type.'),
      preferences: z.string().describe('The user preferences for the properties.'),
    }),
  },
  output: {
    schema: z.object({
      propertyRecommendations: z
        .string()
        .describe('The list of recommended properties, each of them with property features, such as number of bedrooms, location, price range and property type.'),
    }),
  },
  prompt: `You are an expert real estate agent specializing in recommending properties to users based on their search history and preferences.\n\nYou will use this information to recommend properties to the user.\n\nUse the following as the primary source of information about the user.\n\nSearch History: {{{searchHistory}}}\nSaved Properties: {{{savedProperties}}}\nPreferences: {{{preferences}}}\n\nBased on this information, what properties would you recommend to the user?  Return a comma separated list of properties with their features.`,
});

const propertyRecommendationFlow = ai.defineFlow<
  typeof PropertyRecommendationInputSchema,
  typeof PropertyRecommendationOutputSchema
>(
  {
    name: 'propertyRecommendationFlow',
    inputSchema: PropertyRecommendationInputSchema,
    outputSchema: PropertyRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
