// This is an autogenerated file from Firebase Studio. Do not edit.
'use client';

import type { ReactNode } from 'react';
import { APIProvider } from '@vis.gl/react-google-maps';

interface MapsProviderProps {
  children: ReactNode;
}

export function MapsProvider({ children }: MapsProviderProps) {
  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

  if (!apiKey) {
    console.error("Google Maps API Key is missing. Please set NEXT_PUBLIC_GOOGLE_MAPS_API_KEY in your .env file. Map features will be disabled.");
    // Render children without the provider to allow the rest of the app to function
    // You could also render a specific error component here
    return (
        <>
            <div className="container py-4 text-center text-destructive bg-destructive/10 border border-destructive rounded-md">
                <p className="font-semibold">Map Error</p>
                <p className="text-sm">Google Maps API Key is missing. Please configure it in the <code>.env</code> file to enable map functionality.</p>
            </div>
             {/* Render children anyway, but map components might fail */}
            {children}
        </>
        );
  }

  return <APIProvider apiKey={apiKey}>{children}</APIProvider>;
}
